urls:
  a: https://atcoder.jp/contests/abc330/tasks/abc330_a
  b: https://atcoder.jp/contests/abc330/tasks/abc330_b
  c: https://atcoder.jp/contests/abc330/tasks/abc330_c
  d: https://atcoder.jp/contests/abc330/tasks/abc330_d
  e: https://atcoder.jp/contests/abc330/tasks/abc330_e
  f: https://atcoder.jp/contests/abc330/tasks/abc330_f
  g: https://atcoder.jp/contests/abc330/tasks/abc330_g
