urls:
  a: https://atcoder.jp/contests/abc324/tasks/abc324_a
  b: https://atcoder.jp/contests/abc324/tasks/abc324_b
  c: https://atcoder.jp/contests/abc324/tasks/abc324_c
  d: https://atcoder.jp/contests/abc324/tasks/abc324_d
  e: https://atcoder.jp/contests/abc324/tasks/abc324_e
  f: https://atcoder.jp/contests/abc324/tasks/abc324_f
  g: https://atcoder.jp/contests/abc324/tasks/abc324_g
