urls:
  a: https://atcoder.jp/contests/abc332/tasks/abc332_a
  b: https://atcoder.jp/contests/abc332/tasks/abc332_b
  c: https://atcoder.jp/contests/abc332/tasks/abc332_c
  d: https://atcoder.jp/contests/abc332/tasks/abc332_d
  e: https://atcoder.jp/contests/abc332/tasks/abc332_e
  f: https://atcoder.jp/contests/abc332/tasks/abc332_f
  g: https://atcoder.jp/contests/abc332/tasks/abc332_g
