urls:
  a: https://atcoder.jp/contests/abc333/tasks/abc333_a
  b: https://atcoder.jp/contests/abc333/tasks/abc333_b
  c: https://atcoder.jp/contests/abc333/tasks/abc333_c
  d: https://atcoder.jp/contests/abc333/tasks/abc333_d
  e: https://atcoder.jp/contests/abc333/tasks/abc333_e
  f: https://atcoder.jp/contests/abc333/tasks/abc333_f
  g: https://atcoder.jp/contests/abc333/tasks/abc333_g
