version: '3'

services:
  ubuntu:
    container_name: atcoder
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ~/workspace/atcoder:/atcoder
    tty: true
