urls:
  a: https://atcoder.jp/contests/abc329/tasks/abc329_a
  b: https://atcoder.jp/contests/abc329/tasks/abc329_b
  c: https://atcoder.jp/contests/abc329/tasks/abc329_c
  d: https://atcoder.jp/contests/abc329/tasks/abc329_d
  e: https://atcoder.jp/contests/abc329/tasks/abc329_e
  f: https://atcoder.jp/contests/abc329/tasks/abc329_f
  g: https://atcoder.jp/contests/abc329/tasks/abc329_g
