urls:
  a: https://atcoder.jp/contests/abc334/tasks/abc334_a
  b: https://atcoder.jp/contests/abc334/tasks/abc334_b
  c: https://atcoder.jp/contests/abc334/tasks/abc334_c
  d: https://atcoder.jp/contests/abc334/tasks/abc334_d
  e: https://atcoder.jp/contests/abc334/tasks/abc334_e
  f: https://atcoder.jp/contests/abc334/tasks/abc334_f
  g: https://atcoder.jp/contests/abc334/tasks/abc334_g
