urls:
  a: https://atcoder.jp/contests/abc085/tasks/abc085_a
  b: https://atcoder.jp/contests/abc085/tasks/abc085_b
  c: https://atcoder.jp/contests/abc085/tasks/abc085_c
  d: https://atcoder.jp/contests/abc085/tasks/abc085_d
  e: https://atcoder.jp/contests/abc085/tasks/abc085_e
  f: https://atcoder.jp/contests/abc085/tasks/abc085_f
  g: https://atcoder.jp/contests/abc085/tasks/abc085_g
