urls:
  a: https://atcoder.jp/contests/abc325/tasks/abc325_a
  b: https://atcoder.jp/contests/abc325/tasks/abc325_b
  c: https://atcoder.jp/contests/abc325/tasks/abc325_c
  d: https://atcoder.jp/contests/abc325/tasks/abc325_d
  e: https://atcoder.jp/contests/abc325/tasks/abc325_e
  f: https://atcoder.jp/contests/abc325/tasks/abc325_f
  g: https://atcoder.jp/contests/abc325/tasks/abc325_g
